<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        DB::table('users')->insert([
             [
                'id' => 1,
                'firstname' => 'William',
                'lastname' => 'Castillo',
                'username' => 'William Castillo',
                'email' => 'admin@example.com',
                'password' => '$2y$10$IFj6SwqC0Sxrsiv4YkCt.OJv1UV4mZrWuyLoRG7qt47mseP9mJ58u',
                'avatar' => 'no_avatar.png',
                'phone' => '0123456789',
                'role_id' => 1,
                'statut' => 1,
                'is_all_warehouses' => 1,
                'record_view' => 1,
            ]
            // // Global/system users
            [
                'id' => 1,
                'firstname' => 'Super',
                'lastname' => 'Admin',
                'username' => 'superadmin',
                'email' => 'superadmin@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => 'no_avatar.png',
                'phone' => '0123456789',
                'role_id' => 1,
                'statut' => 1,
                'is_all_warehouses' => 1,
                'record_view' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'firstname' => 'Admin',
                'lastname' => 'User',
                'username' => 'admin',
                'email' => 'admin@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 2,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Default one-per-role users
            [
                'id' => 3,
                'firstname' => 'Branch',
                'lastname' => 'Manager',
                'username' => 'branchmanager',
                'email' => 'manager@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'firstname' => 'Accountant',
                'lastname' => 'User',
                'username' => 'accountant',
                'email' => 'accountant@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'firstname' => 'Sales',
                'lastname' => 'Man',
                'username' => 'salesman',
                'email' => 'sales@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'firstname' => 'Cash',
                'lastname' => 'Ier',
                'username' => 'cashier',
                'email' => 'cashier@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Branch-specific users for Warehouse 1 (Al Madina Branch Kamra Road)
            [
                'id' => 7,
                'firstname' => 'Kamra',
                'lastname' => 'Manager',
                'username' => 'kamra_manager',
                'email' => 'kamra.manager@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'firstname' => 'Kamra',
                'lastname' => 'Accountant',
                'username' => 'kamra_accountant',
                'email' => 'kamra.accountant@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'firstname' => 'Kamra',
                'lastname' => 'Sales',
                'username' => 'kamra_sales',
                'email' => 'kamra.sales@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'firstname' => 'Kamra',
                'lastname' => 'Cashier',
                'username' => 'kamra_cashier',
                'email' => 'kamra.cashier@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Branch-specific users for Warehouse 2 (Al Madina Branch Madani Chowk)
            [
                'id' => 11,
                'firstname' => 'Madani',
                'lastname' => 'Manager',
                'username' => 'madani_manager',
                'email' => 'madani.manager@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'firstname' => 'Madani',
                'lastname' => 'Accountant',
                'username' => 'madani_accountant',
                'email' => 'madani.accountant@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'firstname' => 'Madani',
                'lastname' => 'Sales',
                'username' => 'madani_sales',
                'email' => 'madani.sales@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'firstname' => 'Madani',
                'lastname' => 'Cashier',
                'username' => 'madani_cashier',
                'email' => 'madani.cashier@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Branch-specific users for Warehouse 3 (Al Madina Kamra Branch)
            [
                'id' => 15,
                'firstname' => 'Kamra2',
                'lastname' => 'Manager',
                'username' => 'kamra2_manager',
                'email' => 'kamra2.manager@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'firstname' => 'Kamra2',
                'lastname' => 'Accountant',
                'username' => 'kamra2_accountant',
                'email' => 'kamra2.accountant@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'firstname' => 'Kamra2',
                'lastname' => 'Sales',
                'username' => 'kamra2_sales',
                'email' => 'kamra2.sales@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'firstname' => 'Kamra2',
                'lastname' => 'Cashier',
                'username' => 'kamra2_cashier',
                'email' => 'kamra2.cashier@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Branch-specific users for Warehouse 4 (Al Madina Hazro Branch)
            [
                'id' => 19,
                'firstname' => 'Hazro',
                'lastname' => 'Manager',
                'username' => 'hazro_manager',
                'email' => 'hazro.manager@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'firstname' => 'Hazro',
                'lastname' => 'Accountant',
                'username' => 'hazro_accountant',
                'email' => 'hazro.accountant@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'firstname' => 'Hazro',
                'lastname' => 'Sales',
                'username' => 'hazro_sales',
                'email' => 'hazro.sales@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'firstname' => 'Hazro',
                'lastname' => 'Cashier',
                'username' => 'hazro_cashier',
                'email' => 'hazro.cashier@almadina.test',
                'password' => Hash::make('Password123!'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
