<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        $users = [
            [
                'id' => 1,
                'firstname' => 'Super',
                'lastname' => 'Admin',
                'username' => 'superadmin',
                'email' => 'superadmin@al-madinaelectronics.com',
                'password' => Hash::make('Nasir@123'),
                'avatar' => 'no_avatar.png',
                'phone' => '0123456789',
                'role_id' => 1,
                'statut' => 1,
                'is_all_warehouses' => 1,
                'record_view' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'firstname' => 'Admin',
                'lastname' => 'User',
                'username' => 'admin',
                'email' => 'admin@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 2,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'firstname' => 'Branch',
                'lastname' => 'Manager',
                'username' => 'branchmanager',
                'email' => 'manager@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'firstname' => 'Accountant',
                'lastname' => 'User',
                'username' => 'accountant',
                'email' => 'accountant@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'firstname' => 'Sales',
                'lastname' => 'Man',
                'username' => 'salesman',
                'email' => 'sales@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'firstname' => 'Cash',
                'lastname' => 'Ier',
                'username' => 'cashier',
                'email' => 'cashier@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'firstname' => 'Kamra',
                'lastname' => 'Manager',
                'username' => 'kamra_manager',
                'email' => 'kamra.manager@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'firstname' => 'Kamra',
                'lastname' => 'Accountant',
                'username' => 'kamra_accountant',
                'email' => 'kamra.accountant@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'firstname' => 'Kamra',
                'lastname' => 'Sales',
                'username' => 'kamra_sales',
                'email' => 'kamra.sales@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'firstname' => 'Kamra',
                'lastname' => 'Cashier',
                'username' => 'kamra_cashier',
                'email' => 'kamra.cashier@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'firstname' => 'Madani',
                'lastname' => 'Manager',
                'username' => 'madani_manager',
                'email' => 'madani.manager@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'firstname' => 'Madani',
                'lastname' => 'Accountant',
                'username' => 'madani_accountant',
                'email' => 'madani.accountant@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'firstname' => 'Madani',
                'lastname' => 'Sales',
                'username' => 'madani_sales',
                'email' => 'madani.sales@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'firstname' => 'Madani',
                'lastname' => 'Cashier',
                'username' => 'madani_cashier',
                'email' => 'madani.cashier@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'firstname' => 'Kamra2',
                'lastname' => 'Manager',
                'username' => 'kamra2_manager',
                'email' => 'kamra2.manager@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'firstname' => 'Kamra2',
                'lastname' => 'Accountant',
                'username' => 'kamra2_accountant',
                'email' => 'kamra2.accountant@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'firstname' => 'Kamra2',
                'lastname' => 'Sales',
                'username' => 'kamra2_sales',
                'email' => 'kamra2.sales@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'firstname' => 'Kamra2',
                'lastname' => 'Cashier',
                'username' => 'kamra2_cashier',
                'email' => 'kamra2.cashier@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'firstname' => 'Hazro',
                'lastname' => 'Manager',
                'username' => 'hazro_manager',
                'email' => 'hazro.manager@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 3,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'firstname' => 'Hazro',
                'lastname' => 'Accountant',
                'username' => 'hazro_accountant',
                'email' => 'hazro.accountant@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 4,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'firstname' => 'Hazro',
                'lastname' => 'Sales',
                'username' => 'hazro_sales',
                'email' => 'hazro.sales@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 5,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'firstname' => 'Hazro',
                'lastname' => 'Cashier',
                'username' => 'hazro_cashier',
                'email' => 'hazro.cashier@al-madinaelectronics.com',
                'password' => Hash::make('password'),
                'avatar' => null,
                'phone' => null,
                'role_id' => 6,
                'statut' => 1,
                'is_all_warehouses' => 0,
                'record_view' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Ensure every user array has the same keys (safety) and then insert
        $defaultKeys = [
            'id', 'firstname', 'lastname', 'username', 'email', 'password', 'avatar', 'phone',
            'role_id', 'statut', 'is_all_warehouses', 'record_view', 'created_at', 'updated_at'
        ];

        $normalized = array_map(function ($u) use ($now, $defaultKeys) {
            foreach ($defaultKeys as $k) {
                if (!array_key_exists($k, $u)) {
                    if ($k === 'created_at' || $k === 'updated_at') {
                        $u[$k] = $now;
                    } elseif ($k === 'password') {
                        $u[$k] = Hash::make('password');
                    } else {
                        $u[$k] = null;
                    }
                }
            }
            // order keys consistently
            $ordered = [];
            foreach ($defaultKeys as $k) {
                $ordered[$k] = $u[$k];
            }
            return $ordered;
        }, $users);

        DB::table('users')->insert($normalized);
    }
}
